### ISSUE TITLE
Mistake in in-silico digestion of fastq reads?

### ISSUE THREAD

**Issue by dmalzl** [Hughes-Genome-Group/CCseqBasicS#1]
Dear Developers,

I am currently trying to wrap my head around what your pipeline is doing from start to finish to troubleshoot an ongoing TriC experiment. In order to do so I just wanted to know how the in-silico digestion of the raw read pairs with NlaIII looked like after alignment. As I implemented the digestion myself and compared it to your `nlaIIIcutReads4.pl` scirpt, I noticed that there might be a problem with you implementation. My interpretation of the problem is as follows:

The cut sequence of the NlaIII restriction enzyme being
```
5'-... CATG|...-3'
3'-...|GTAC ...-5'
```
where `|` indicates the cutsite. Paired-end sequencing of a given read occurs as follows:
```
5'-AAACATGAAAA-3'                        read1
5'-AAACATGAAAAGGGGGCCCCTTTTTTCATGAAAA-3' +
3'-TTTGTACTTTTCCCCCGGGGAAAAAAGTACTTTT-5' -
                    3'-AAAAAAGATCTTTT-5' read2
```

According to this model, read2 is always the reverse complement of the 3'-end of the fragment and thus also contains the reverse complement of the cutting sequence (GTAC instead of CATG).
Consequently, this requires to find the pattern GTAC in read2 rather than CATG to perform correct digestion of the read pair. However, your perl script does not seem to account for this. 
Please correct me if I am wrong, as I am not a perl native and it is hard for me to read anyway. If not I would like you to correct this mistake.

**Comment by rschwess** [comment]
Hi mnmldani,

The enzymecutReads4.pl scripts process fastq file reads. In fastq format the reads from both + and - strand are reported in their respective 5' to 3' orientation. So even on the minus strand reads you are still looking for CATG. 

In your model read2 does not match the - strand sequence your read2 should be :
`3'-AAAAAAGTACTTTT-5' read2`

Let me know if that clears things up.

**Comment by dmalzl** [comment]
Ahhh. That's what I call a revelation, but it makes sense. So just to recapitulate, Fastq entries for a given read is always from left (5') to right (3'), which would effectively make read2 a reverse complement and thus only CATG needs to be looked for. Okay, so the mistake was totally in my thinking process. Sorry for bothering.

**Comment by rschwess** [comment]
Yes sounds right now and no worries!
